```{r}
getwd()
setwd("~/Udacity Data Analisys/Lesson 4")
pf <- read.csv("pseudo_facebook.tsv", sep = "\t")
rm(reddit)


```


```{r}
install.packages("ggplot2")
library(ggplot2)
names(pf)

qplot(x= dob_day, data = pf, binwidth=2) +
  scale_x_continuous(breaks=1:31) +
  facet_wrap(~dob_month, ncol = 3)

```

```{r}
qplot(x=friend_count, data = subset(pf, !is.na(gender)), binwidth= 25) +
  scale_x_continuous(limits = c(0,1000), breaks = seq(0, 1000, 100)) +
  facet_wrap(~gender)
```

```{r}
by(pf$friend_count, pf$gender, summary)
```
```{r}
qplot(x= tenure/365, data = pf, binwidth = .25, 
      xlab = "years in facebook",
      ylab = "Number of users",
      color = I("black"), fill = I('#099DD9'))
```

## User Ages
```{r}
qplot(x = age, data = pf, binwidth = 3,
      color = I("white"), fill = I('#099DD9'),
      xlab = "Age of users",
      ylab = "Number of users",) +
  scale_x_continuous( breaks = seq(0, 100, 10))
```
```{r}
getwd()
qplot(x= friend_count, data = pf)
summary(pf$friend_count)
summary(log10(pf$friend_count + 1))
summary(sqrt(pf$friend_count))
```
```{r}
install.packages("gridExtra")
library("gridExtra")

p1 <- qplot(x = friend_count, data = pf)
p2 <- qplot(x = friend_count, data = pf) + scale_x_log10()
p3 <- qplot(x = friend_count, data = pf) + scale_x_sqrt()
grid.arrange(p1, p2, p3)
```

```{r}
qplot(x= friend_count, y= ..count../sum(..count..)
        , data = subset(pf, !is.na(gender)),
      binwidth = 10, geom = "freqpoly", color = gender) +
  scale_x_continuous(lim = c(0, 1000), breaks = seq(0, 1000, 50))
```
+
  scale_x_continuous( breaks = seq(0, 100, 10))
  binwidth = 0.25,
```{r}
qplot(x = www_likes, data = pf, binwidth = 15,
      color = I("white"), fill = I('#099DD9'),
      xlab = "Number of likes",
      ylab = "Number of users") +
  scale_x_continuous( breaks = seq(0, 1000, 100), limits = c(0,500)) +
  scale_y_continuous(limits = c(0,7500))
```

```{r}
qplot(x = www_likes, data = subset(pf, !is.na(gender)),
      geom = 'freqpoly', color = gender) +
  scale_x_continuous() +
  scale_x_log10()
```
```{r}

sum(pf[pf$gender == "female",]$www_likes, na.rm = TRUE)
sum(pf[pf$gender == "male",]$www_likes, na.rm = TRUE)

by(pf$www_likes, pf$gender, sum)
```
```{r}
qplot(x = gender, y =  friend_count,
  geom = "boxplot", data = subset(pf, !is.na(gender)))+
  scale_y_continuous(limits = c(0, 1000))

qplot(x = gender, y =  friendships_initiated,
  geom = "boxplot", data = subset(pf, !is.na(gender)))+
  coord_cartesian(ylim = c(0, 250))

by(pf$friendships_initiated, pf$gender, summary)
```

```{r}
mobile_check_in <- NA
pf$mobile_check_in <- ifelse(pf$mobile_likes > 0, 1, 0)
pf$mobile_check_in <- factor(pf$mobile_check_in)
summary(pf$mobile_check_in)
```

